name: '[Staging] Publish npm Package'

on:
    push:
        branches: [development]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: '20'
            - run: npm i -g pnpm
            - run: pnpm i --frozen-lockfile
            - uses: JS-DevTools/npm-publish@v3
              id: publish
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  tag: staging
                  strategy: upgrade
            - run: echo "Package v${{ steps.publish.outputs.version }} published - https://www.npmjs.com/package/@raphaelbernhart/nuxt-base-layer/v/${{ steps.publish.outputs.version }}"
